const analog = document.querySelector('.analog_clock');
const digital = document.querySelector('.digital-clock');
const switchA = document.getElementById('analog');
const switchD = document.getElementById('digital');
const switchController = document.querySelector('.switch');

analog.addEventListener('click', ()=> {
    if (analog.classList.contains('on')) {
        analog.classList.add('off');
        analog.classList.remove('on');
        analog.style.display = "none";
        digital.style.display = "block";
        switchA.style.background = "rgba(0,0,0,0.3)";
        switchD.style.background = "#fff";
    } 
});
digital.addEventListener('click', ()=> {
    if (analog.classList.contains('off')) {
        analog.classList.remove('off');
        analog.classList.add('on');
        analog.style.display = "block";
        digital.style.display = "none";
        switchD.style.background = "rgba(0,0,0,0.3)";
        switchA.style.background = "#fff";
    }
});
switchController.addEventListener('click', ()=> {
    if (analog.classList.contains('on')) {
        analog.classList.add('off');
        analog.classList.remove('on');
        analog.style.display = "none";
        digital.style.display = "block";
        switchA.style.background = "rgba(0,0,0,0.3)";
        switchD.style.background = "#fff";
    } else {
        analog.classList.remove('off');
        analog.classList.add('on');
        analog.style.display = "block";
        digital.style.display = "none";
        switchD.style.background = "rgba(0,0,0,0.3)";
        switchA.style.background = "#fff";
    }
});


const secDiv = document.getElementById('seconds');
const minDiv = document.getElementById('minutes');
const hourDiv = document.getElementById('hours');

setInterval(updateTime, 1000);

function updateTime(){
    let date= new Date();
    let sec = date.getSeconds() / 60;
    let min = (date.getMinutes() + sec) / 60;
    let hour = (date.getHours() + min) / 12;

    secDiv.style.transform = "rotate("+(sec * 360)+"deg)";
    minDiv.style.transform = "rotate(" +(min * 360)+"deg)";
    hourDiv.style.transform = "rotate(" +(hour * 360)+"deg)";
}

updateTime();

const a1 = document.getElementById('a-1');
const a2 = document.getElementById('a-2');
const a3 = document.getElementById('a-3');
const a4 = document.getElementById('a-4');
const a5 = document.getElementById('a-5');
const a6 = document.getElementById('a-6');
const a7 = document.getElementById('a-7');
const a11 = document.getElementById('a-1-1');
const a12 = document.getElementById('a-1-2');
const a21 = document.getElementById('a-2-1');
const a22 = document.getElementById('a-2-2');
const a31 = document.getElementById('a-3-1');
const a32 = document.getElementById('a-3-2');
const a41 = document.getElementById('a-4-1');
const a42 = document.getElementById('a-4-2');
const a51 = document.getElementById('a-5-1');
const a52 = document.getElementById('a-5-2');
const a61 = document.getElementById('a-6-1');
const a62 = document.getElementById('a-6-2');
const a71 = document.getElementById('a-7-1');
const a72 = document.getElementById('a-7-2');
const b1 = document.getElementById('b-1');
const b2 = document.getElementById('b-2');
const b3 = document.getElementById('b-3');
const b4 = document.getElementById('b-4');
const b5 = document.getElementById('b-5');
const b6 = document.getElementById('b-6');
const b7 = document.getElementById('b-7');
const b11 = document.getElementById('b-1-1');
const b12 = document.getElementById('b-1-2');
const b21 = document.getElementById('b-2-1');
const b22 = document.getElementById('b-2-2');
const b31 = document.getElementById('b-3-1');
const b32 = document.getElementById('b-3-2');
const b41 = document.getElementById('b-4-1');
const b42 = document.getElementById('b-4-2');
const b51 = document.getElementById('b-5-1');
const b52 = document.getElementById('b-5-2');
const b61 = document.getElementById('b-6-1');
const b62 = document.getElementById('b-6-2');
const b71 = document.getElementById('b-7-1');
const b72 = document.getElementById('b-7-2');
const c1 = document.getElementById('c-1');
const c2 = document.getElementById('c-2');
const c3 = document.getElementById('c-3');
const c4 = document.getElementById('c-4');
const c5 = document.getElementById('c-5');
const c6 = document.getElementById('c-6');
const c7 = document.getElementById('c-7');
const c11 = document.getElementById('c-1-1');
const c12 = document.getElementById('c-1-2');
const c21 = document.getElementById('c-2-1');
const c22 = document.getElementById('c-2-2');
const c31 = document.getElementById('c-3-1');
const c32 = document.getElementById('c-3-2');
const c41 = document.getElementById('c-4-1');
const c42 = document.getElementById('c-4-2');
const c51 = document.getElementById('c-5-1');
const c52 = document.getElementById('c-5-2');
const c61 = document.getElementById('c-6-1');
const c62 = document.getElementById('c-6-2');
const c71 = document.getElementById('c-7-1');
const c72 = document.getElementById('c-7-2');
const d1 = document.getElementById('d-1');
const d2 = document.getElementById('d-2');
const d3 = document.getElementById('d-3');
const d4 = document.getElementById('d-4');
const d5 = document.getElementById('d-5');
const d6 = document.getElementById('d-6');
const d7 = document.getElementById('d-7');
const d11 = document.getElementById('d-1-1');
const d12 = document.getElementById('d-1-2');
const d21 = document.getElementById('d-2-1');
const d22 = document.getElementById('d-2-2');
const d31 = document.getElementById('d-3-1');
const d32 = document.getElementById('d-3-2');
const d41 = document.getElementById('d-4-1');
const d42 = document.getElementById('d-4-2');
const d51 = document.getElementById('d-5-1');
const d52 = document.getElementById('d-5-2');
const d61 = document.getElementById('d-6-1');
const d62 = document.getElementById('d-6-2');
const d71 = document.getElementById('d-7-1');
const d72 = document.getElementById('d-7-2');
const dot1 = document.getElementById('dot1');
const dot2 = document.getElementById('dot2');

setInterval(updateAnalogClock, 500);

function updateAnalogClock() {
    let date = new Date();
    let hours = date.getHours();
    let minutes = date.getMinutes();
    const originalColor = "#767178";

    if (hours == 1 || hours == 11 || hours == 21) {
        b1.style.background =  originalColor;
        b2.style.background =  originalColor;
        b3.style.background =  originalColor;
        b4.style.background =  originalColor;
        b5.style.background =  originalColor;
        b6.style.background = "#fff";
        b7.style.background = "#fff";
        b11.style.background = originalColor;
        b12.style.background = originalColor;
        b21.style.background = originalColor;
        b22.style.background = originalColor;
        b31.style.background = originalColor;
        b32.style.background = originalColor;
        b41.style.background = originalColor;
        b42.style.background = originalColor;
        b51.style.background = originalColor;
        b52.style.background = originalColor;
        b61.style.background = "#fff";
        b62.style.background = "#fff";
        b71.style.background = "#fff";
        b72.style.background = "#fff";
    } else if (hours == 2 || hours == 12 || hours == 22 ) {
        b1.style.background = "#fff";
        b2.style.background = "#fff";
        b3.style.background = "#fff";
        b4.style.background = originalColor;
        b5.style.background = "#fff";
        b6.style.background = "#fff";
        b7.style.background = originalColor;
        b11.style.background = "#fff";
        b12.style.background = "#fff";
        b21.style.background = "#fff";
        b22.style.background = "#fff";
        b31.style.background = "#fff";
        b32.style.background = "#fff";
        b41.style.background = originalColor;
        b42.style.background = originalColor;
        b51.style.background = "#fff";
        b52.style.background = "#fff";
        b61.style.background = "#fff";
        b62.style.background = "#fff";
        b71.style.background = originalColor;
        b72.style.background = originalColor;
    } else if (hours == 3 || hours == 13 || hours == 23) {
        b1.style.background = "#fff";
        b2.style.background = "#fff";
        b3.style.background = "#fff";
        b4.style.background = originalColor;
        b5.style.background = originalColor;
        b6.style.background = "#fff";
        b7.style.background = "#fff";
        b11.style.background = "#fff";
        b12.style.background = "#fff";
        b21.style.background = "#fff";
        b22.style.background = "#fff";
        b31.style.background = "#fff";
        b32.style.background = "#fff";
        b41.style.background = originalColor;
        b42.style.background = originalColor;
        b51.style.background = originalColor;
        b52.style.background = originalColor;
        b61.style.background = "#fff";
        b62.style.background = "#fff";
        b71.style.background = "#fff";
        b72.style.background = "#fff";
    } else if (hours == 4 || hours == 14 ) {
        b1.style.background = originalColor;
        b2.style.background = "#fff";
        b3.style.background = originalColor;
        b4.style.background = "#fff";
        b5.style.background = originalColor;
        b6.style.background = "#fff";
        b7.style.background = "#fff";
        b11.style.background = originalColor;
        b12.style.background = originalColor;
        b21.style.background = "#fff";
        b22.style.background = "#fff";
        b31.style.background = originalColor;
        b32.style.background = originalColor;
        b41.style.background = "#fff";
        b42.style.background = "#fff";
        b51.style.background = originalColor;
        b52.style.background = originalColor;
        b61.style.background = "#fff";
        b62.style.background = "#fff";
        b71.style.background = "#fff";
        b72.style.background = "#fff";
    } else if (hours == 5 || hours == 15 ) {
        b1.style.background = "#fff";
        b2.style.background = "#fff";
        b3.style.background = "#fff";
        b4.style.background = "#fff";
        b5.style.background = originalColor;
        b6.style.background = originalColor;
        b7.style.background = "#fff";
        b11.style.background = "#fff";
        b12.style.background = "#fff";
        b21.style.background = "#fff";
        b22.style.background = "#fff";
        b31.style.background = "#fff";
        b32.style.background = "#fff";
        b41.style.background = "#fff";
        b42.style.background = "#fff";
        b51.style.background = originalColor;
        b52.style.background = originalColor;
        b61.style.background = originalColor;
        b62.style.background = originalColor;
        b71.style.background = "#fff";
        b72.style.background = "#fff";
    } else if (hours == 6 || hours == 16 ) {
        b1.style.background = "#fff";
        b2.style.background = "#fff";
        b3.style.background = "#fff";
        b4.style.background = "#fff";
        b5.style.background = "#fff";
        b6.style.background = originalColor;
        b7.style.background = "#fff";
        b11.style.background = "#fff";
        b12.style.background = "#fff";
        b21.style.background = "#fff";
        b22.style.background = "#fff";
        b31.style.background = "#fff";
        b32.style.background = "#fff";
        b41.style.background = "#fff";
        b42.style.background = "#fff";
        b51.style.background = "#fff";
        b52.style.background = "#fff";
        b61.style.background = originalColor;
        b62.style.background = originalColor;
        b71.style.background = "#fff";
        b72.style.background = "#fff";
    } else if (hours == 7 || hours == 17 ) {
        b1.style.background = "#fff";
        b2.style.background = originalColor;
        b3.style.background = originalColor;
        b4.style.background = "#fff";
        b5.style.background = originalColor;
        b6.style.background = "#fff";
        b7.style.background = "#fff";
        b11.style.background = "#fff";
        b12.style.background = "#fff";
        b21.style.background = originalColor;
        b22.style.background = originalColor;
        b31.style.background = originalColor;
        b32.style.background = originalColor;
        b41.style.background = "#fff";
        b42.style.background = "#fff";
        b51.style.background = originalColor;
        b52.style.background = originalColor;
        b61.style.background = "#fff";
        b62.style.background = "#fff";
        b71.style.background = "#fff";
        b72.style.background = "#fff";
    } else if (hours == 8 || hours == 18 ) {
        b1.style.background = "#fff";
        b2.style.background = "#fff";
        b3.style.background = "#fff";
        b4.style.background = "#fff";
        b5.style.background = "#fff";
        b6.style.background = "#fff";
        b7.style.background = "#fff";
        b11.style.background = "#fff";
        b12.style.background = "#fff";
        b21.style.background = "#fff";
        b22.style.background = "#fff";
        b31.style.background = "#fff";
        b32.style.background = "#fff";
        b41.style.background = "#fff";
        b42.style.background = "#fff";
        b51.style.background = "#fff";
        b52.style.background = "#fff";
        b61.style.background = "#fff";
        b62.style.background = "#fff";
        b71.style.background = "#fff";
        b72.style.background = "#fff";
    } else if (hours == 9 || hours == 19 ) {
        b1.style.background = "#fff";
        b2.style.background = "#fff";
        b3.style.background = "#fff";
        b4.style.background = "#fff";
        b5.style.background = originalColor;
        b6.style.background = "#fff";
        b7.style.background = "#fff";
        b11.style.background = "#fff";
        b12.style.background = "#fff";
        b21.style.background = "#fff";
        b22.style.background = "#fff";
        b31.style.background = "#fff";
        b32.style.background = "#fff";
        b41.style.background = "#fff";
        b42.style.background = "#fff";
        b51.style.background = originalColor;
        b52.style.background = originalColor;
        b61.style.background = "#fff";
        b62.style.background = "#fff";
        b71.style.background = "#fff";
        b72.style.background = "#fff";
    } else {
        b1.style.background = "#fff";
        b2.style.background = originalColor;
        b3.style.background = "#fff";
        b4.style.background = "#fff";
        b5.style.background = "#fff";
        b6.style.background = "#fff";
        b7.style.background = "#fff";
        b11.style.background = "#fff";
        b12.style.background = "#fff";
        b21.style.background = originalColor;
        b22.style.background = originalColor;
        b31.style.background = "#fff";
        b32.style.background = "#fff";
        b41.style.background = "#fff";
        b42.style.background = "#fff";
        b51.style.background = "#fff";
        b52.style.background = "#fff";
        b61.style.background = "#fff";
        b62.style.background = "#fff";
        b71.style.background = "#fff";
        b72.style.background = "#fff";
    }

    if (hours < 10) {
        a1.style.background = "#fff";
        a2.style.background = originalColor;
        a3.style.background = "#fff";
        a4.style.background = "#fff";
        a5.style.background = "#fff";
        a6.style.background = "#fff";
        a7.style.background = "#fff";
        a11.style.background = "#fff";
        a12.style.background = "#fff";
        a21.style.background = originalColor;
        a22.style.background = originalColor;
        a31.style.background = "#fff";
        a32.style.background = "#fff";
        a41.style.background = "#fff";
        a42.style.background = "#fff";
        a51.style.background = "#fff";
        a52.style.background = "#fff";
        a61.style.background = "#fff";
        a62.style.background = "#fff";
        a71.style.background = "#fff";
        a72.style.background = "#fff";
    } else if (hours < 20) {
        a1.style.background = originalColor ;
        a2.style.background = originalColor ;
        a3.style.background = originalColor ;
        a4.style.background = originalColor ;
        a5.style.background = originalColor ;
        a6.style.background = "#fff";
        a7.style.background = "#fff";
        a11.style.background = originalColor ;
        a12.style.background = originalColor ;
        a21.style.background = originalColor ;
        a22.style.background = originalColor ;
        a31.style.background = originalColor ;
        a32.style.background = originalColor ;
        a41.style.background = originalColor ;
        a42.style.background = originalColor ;
        a51.style.background = originalColor ;
        a52.style.background = originalColor ;
        a61.style.background = "#fff";
        a62.style.background = "#fff";
        a71.style.background = "#fff";
        a72.style.background = "#fff";
    } else {
        a1.style.background = "#fff";
        a2.style.background = "#fff";
        a3.style.background = "#fff";
        a4.style.background = originalColor;
        a5.style.background = "#fff";
        a6.style.background = "#fff";
        a7.style.background = originalColor;
        a11.style.background = "#fff";
        a12.style.background = "#fff";
        a21.style.background = "#fff";
        a22.style.background = "#fff";
        a31.style.background = "#fff";
        a32.style.background = "#fff";
        a41.style.background = originalColor;
        a42.style.background = originalColor;
        a51.style.background = "#fff";
        a52.style.background = "#fff";
        a61.style.background = "#fff";
        a62.style.background = "#fff";
        a71.style.background = originalColor;
        a72.style.background = originalColor;
    }
    
    if (minutes == 1 || minutes == 11 || minutes == 21 || minutes == 31 || minutes == 41 || minutes == 51) {
        d1.style.background = originalColor;
        d2.style.background = originalColor;
        d3.style.background = originalColor;
        d4.style.background = originalColor;
        d5.style.background = originalColor;
        d6.style.background = "#fff";
        d7.style.background = "#fff";
        d11.style.background = originalColor;
        d12.style.background = originalColor;
        d21.style.background = originalColor;
        d22.style.background = originalColor;
        d31.style.background = originalColor;
        d32.style.background = originalColor;
        d41.style.background = originalColor;
        d42.style.background = originalColor;
        d51.style.background = originalColor;
        d52.style.background = originalColor;
        d61.style.background = "#fff";
        d62.style.background = "#fff";
        d71.style.background = "#fff";
        d72.style.background = "#fff";
    } else if (minutes == 2 || minutes == 12 || minutes == 22 || minutes == 32 || minutes == 42 || minutes == 52) {
        d1.style.background = "#fff";
        d2.style.background = "#fff";
        d3.style.background = "#fff";
        d4.style.background = originalColor;
        d5.style.background = "#fff";
        d6.style.background = "#fff";
        d7.style.background = originalColor;
        d11.style.background = "#fff";
        d12.style.background = "#fff";
        d21.style.background = "#fff";
        d22.style.background = "#fff";
        d31.style.background = "#fff";
        d32.style.background = "#fff";
        d41.style.background = originalColor;
        d42.style.background = originalColor;
        d51.style.background = "#fff";
        d52.style.background = "#fff";
        d61.style.background = "#fff";
        d62.style.background = "#fff";
        d71.style.background = originalColor;
        d72.style.background = originalColor;
    } else if (minutes == 3 || minutes == 13 || minutes == 23 || minutes == 33 || minutes == 43 || minutes == 53) {
        d1.style.background = "#fff";
        d2.style.background = "#fff";
        d3.style.background = "#fff";
        d4.style.background = originalColor;
        d5.style.background = originalColor;
        d6.style.background = "#fff";
        d7.style.background = "#fff";
        d11.style.background = "#fff";
        d12.style.background = "#fff";
        d21.style.background = "#fff";
        d22.style.background = "#fff";
        d31.style.background = "#fff";
        d32.style.background = "#fff";
        d41.style.background = originalColor;
        d42.style.background = originalColor;
        d51.style.background = originalColor;
        d52.style.background = originalColor;
        d61.style.background = "#fff";
        d62.style.background = "#fff";
        d71.style.background = "#fff";
        d72.style.background = "#fff";
    } else if (minutes == 4 || minutes == 14 || minutes == 24 || minutes == 34 || minutes == 44 || minutes == 54) {
        d1.style.background = originalColor;
        d2.style.background = "#fff";
        d3.style.background = originalColor;
        d4.style.background = "#fff";
        d5.style.background = originalColor;
        d6.style.background = "#fff";
        d7.style.background = "#fff";
        d11.style.background = originalColor;
        d12.style.background = originalColor;
        d21.style.background = "#fff";
        d22.style.background = "#fff";
        d31.style.background = originalColor;
        d32.style.background = originalColor;
        d41.style.background = "#fff";
        d42.style.background = "#fff";
        d51.style.background = originalColor;
        d52.style.background = originalColor;
        d61.style.background = "#fff";
        d62.style.background = "#fff";
        d71.style.background = "#fff";
        d72.style.background = "#fff";
    } else if (minutes == 5 || minutes == 15|| minutes == 25 || minutes == 35 || minutes == 45 || minutes == 55) {
        d1.style.background = "#fff";
        d2.style.background = "#fff";
        d3.style.background = "#fff";
        d4.style.background = "#fff";
        d5.style.background = originalColor;
        d6.style.background = originalColor;
        d7.style.background = "#fff";
        d11.style.background = "#fff";
        d12.style.background = "#fff";
        d21.style.background = "#fff";
        d22.style.background = "#fff";
        d31.style.background = "#fff";
        d32.style.background = "#fff";
        d41.style.background = "#fff";
        d42.style.background = "#fff";
        d51.style.background = originalColor;
        d52.style.background = originalColor;
        d61.style.background = originalColor;
        d62.style.background = originalColor;
        d71.style.background = "#fff";
        d72.style.background = "#fff";
    } else if (minutes == 6 || minutes == 16 || minutes == 26 || minutes == 36 || minutes == 46 || minutes == 56) {
        d1.style.background = "#fff";
        d2.style.background = "#fff";
        d3.style.background = "#fff";
        d4.style.background = "#fff";
        d5.style.background = "#fff";
        d6.style.background = originalColor;
        d7.style.background = "#fff";
        d11.style.background = "#fff";
        d12.style.background = "#fff";
        d21.style.background = "#fff";
        d22.style.background = "#fff";
        d31.style.background = "#fff";
        d32.style.background = "#fff";
        d41.style.background = "#fff";
        d42.style.background = "#fff";
        d51.style.background = "#fff";
        d52.style.background = "#fff";
        d61.style.background = originalColor;
        d62.style.background = originalColor;
        d71.style.background = "#fff";
        d72.style.background = "#fff";
    } else if (minutes == 7 || minutes == 17 || minutes == 27 || minutes == 37 || minutes == 47 || minutes == 57) {
        d1.style.background = "#fff";
        d2.style.background = originalColor;
        d3.style.background = originalColor;
        d4.style.background = "#fff";
        d5.style.background = originalColor;
        d6.style.background = "#fff";
        d7.style.background = "#fff";
        d11.style.background = "#fff";
        d12.style.background = "#fff";
        d21.style.background = originalColor;
        d22.style.background = originalColor;
        d31.style.background = originalColor;
        d32.style.background = originalColor;
        d41.style.background = "#fff";
        d42.style.background = "#fff";
        d51.style.background = originalColor;
        d52.style.background = originalColor;
        d61.style.background = "#fff";
        d62.style.background = "#fff";
        d71.style.background = "#fff";
        d72.style.background = "#fff";
    } else if (minutes == 8 || minutes == 18 || minutes == 28 || minutes == 38 || minutes == 48 || minutes == 58) {
        d1.style.background = "#fff";
        d2.style.background = "#fff";
        d3.style.background = "#fff";
        d4.style.background = "#fff";
        d5.style.background = "#fff";
        d6.style.background = "#fff";
        d7.style.background = "#fff";
        d11.style.background = "#fff";
        d12.style.background = "#fff";
        d21.style.background = "#fff";
        d22.style.background = "#fff";
        d31.style.background = "#fff";
        d32.style.background = "#fff";
        d41.style.background = "#fff";
        d42.style.background = "#fff";
        d51.style.background = "#fff";
        d52.style.background = "#fff";
        d61.style.background = "#fff";
        d62.style.background = "#fff";
        d71.style.background = "#fff";
        d72.style.background = "#fff";
    } else if (minutes == 9 || minutes == 19 || minutes == 29 || minutes == 39 || minutes == 49 || minutes == 59) {
        d1.style.background = "#fff";
        d2.style.background = "#fff";
        d3.style.background = "#fff";
        d4.style.background = "#fff";
        d5.style.background = originalColor;
        d6.style.background = "#fff";
        d7.style.background = "#fff";
        d11.style.background = "#fff";
        d12.style.background = "#fff";
        d21.style.background = "#fff";
        d22.style.background = "#fff";
        d31.style.background = "#fff";
        d32.style.background = "#fff";
        d41.style.background = "#fff";
        d42.style.background = "#fff";
        d51.style.background = originalColor;
        d52.style.background = originalColor;
        d61.style.background = "#fff";
        d62.style.background = "#fff";
        d71.style.background = "#fff";
        d72.style.background = "#fff";
    } else {
        d1.style.background = "#fff";
        d2.style.background = originalColor;
        d3.style.background = "#fff";
        d4.style.background = "#fff";
        d5.style.background = "#fff";
        d6.style.background = "#fff";
        d7.style.background = "#fff";
        d11.style.background = "#fff";
        d12.style.background = "#fff";
        d21.style.background = originalColor;
        d22.style.background = originalColor;
        d31.style.background = "#fff";
        d32.style.background = "#fff";
        d41.style.background = "#fff";
        d42.style.background = "#fff";
        d51.style.background = "#fff";
        d52.style.background = "#fff";
        d61.style.background = "#fff";
        d62.style.background = "#fff";
        d71.style.background = "#fff";
        d72.style.background = "#fff";
    }

    if (minutes < 10) {
        c1.style.background = "#fff";
        c2.style.background = originalColor;
        c3.style.background = "#fff";
        c4.style.background = "#fff";
        c5.style.background = "#fff";
        c6.style.background = "#fff";
        c7.style.background = "#fff";
        c11.style.background = "#fff";
        c12.style.background = "#fff";
        c21.style.background = originalColor;
        c22.style.background = originalColor;
        c31.style.background = "#fff";
        c32.style.background = "#fff";
        c41.style.background = "#fff";
        c42.style.background = "#fff";
        c51.style.background = "#fff";
        c52.style.background = "#fff";
        c61.style.background = "#fff";
        c62.style.background = "#fff";
        c71.style.background = "#fff";
        c72.style.background = "#fff";
    } else if (minutes < 20) {
        c1.style.background = originalColor;
        c2.style.background = originalColor;
        c3.style.background = originalColor;
        c4.style.background = originalColor;
        c5.style.background = originalColor;
        c6.style.background = "#fff";
        c7.style.background = "#fff";
        c11.style.background = originalColor;
        c12.style.background = originalColor;
        c21.style.background = originalColor;
        c22.style.background = originalColor;
        c31.style.background = originalColor;
        c32.style.background = originalColor;
        c41.style.background = originalColor;
        c42.style.background = originalColor;
        c51.style.background = originalColor;
        c52.style.background = originalColor;
        c61.style.background = "#fff";
        c62.style.background = "#fff";
        c71.style.background = "#fff";
        c72.style.background = "#fff";
    } else if (minutes < 30){
        c1.style.background = "#fff";
        c2.style.background = "#fff";
        c3.style.background = "#fff";
        c4.style.background = originalColor;
        c5.style.background = "#fff";
        c6.style.background = "#fff";
        c7.style.background = originalColor;
        c11.style.background = "#fff";
        c12.style.background = "#fff";
        c21.style.background = "#fff";
        c22.style.background = "#fff";
        c31.style.background = "#fff";
        c32.style.background = "#fff";
        c41.style.background = originalColor;
        c42.style.background = originalColor;
        c51.style.background = "#fff";
        c52.style.background = "#fff";
        c61.style.background = "#fff";
        c62.style.background = "#fff";
        c71.style.background = originalColor;
        c72.style.background = originalColor;
    } else if (minutes < 40) {
        c1.style.background = "#fff";
        c2.style.background = "#fff";
        c3.style.background = "#fff";
        c4.style.background = originalColor;
        c5.style.background = originalColor;
        c6.style.background = "#fff";
        c7.style.background = "#fff";
        c11.style.background = "#fff";
        c12.style.background = "#fff";
        c21.style.background = "#fff";
        c22.style.background = "#fff";
        c31.style.background = "#fff";
        c32.style.background = "#fff";
        c41.style.background = originalColor;
        c42.style.background = originalColor;
        c51.style.background = originalColor;
        c52.style.background = originalColor;
        c61.style.background = "#fff";
        c62.style.background = "#fff";
        c71.style.background = "#fff";
        c72.style.background = "#fff";
    } else if (minutes < 50) {
        c1.style.background = originalColor;
        c2.style.background = "#fff";
        c3.style.background = originalColor;
        c4.style.background = "#fff";
        c5.style.background = originalColor;
        c6.style.background = "#fff";
        c7.style.background = "#fff";
        c11.style.background = originalColor;
        c12.style.background = originalColor;
        c21.style.background = "#fff";
        c22.style.background = "#fff";
        c31.style.background = originalColor;
        c32.style.background = originalColor;
        c41.style.background = "#fff";
        c42.style.background = "#fff";
        c51.style.background = originalColor;
        c52.style.background = originalColor;
        c61.style.background = "#fff";
        c62.style.background = "#fff";
        c71.style.background = "#fff";
        c72.style.background = "#fff";
    } else {
        c1.style.background = "#fff";
        c2.style.background = "#fff";
        c3.style.background = "#fff";
        c4.style.background = "#fff";
        c5.style.background = originalColor;
        c6.style.background = originalColor;
        c7.style.background = "#fff";
        c11.style.background = "#fff";
        c12.style.background = "#fff";
        c21.style.background = "#fff";
        c22.style.background = "#fff";
        c31.style.background = "#fff";
        c32.style.background = "#fff";
        c41.style.background = "#fff";
        c42.style.background = "#fff";
        c51.style.background = originalColor;
        c52.style.background = originalColor;
        c61.style.background = originalColor;
        c62.style.background = originalColor;
        c71.style.background = "#fff";
        c72.style.background = "#fff";
    }

    if (dot1.classList.contains('off')) {
        dot1.classList.add('on');
        dot1.classList.remove('off');
        dot1.style.background = "#fff";
        dot2.style.background = "#fff";
    } else {
        dot1.classList.add('off');
        dot1.classList.remove('on');
        dot1.style.background = "#767178";
        dot2.style.background = "#767178";
    }
}

updateAnalogClock();





